// Code generated by 'yaegi extract github.com/hulutech-web/goravel-tinker/funcs/query'. DO NOT EDIT.

package symbols

import (
	"github.com/hulutech-web/goravel-tinker/funcs/query"
	"reflect"
)

func init() {
	Symbols["github.com/hulutech-web/goravel-tinker/funcs/query/query"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BootMS": reflect.ValueOf(query.BootMS),
		"Clear":  reflect.ValueOf(query.Clear),
	}
}
