// Code generated by 'yaegi extract github.com/goravel/framework/database/orm'. DO NOT EDIT.

package symbols

import (
	"github.com/goravel/framework/database/orm"
	"reflect"
)

func init() {
	Symbols["github.com/goravel/framework/database/orm/orm"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Associations":      reflect.ValueOf(orm.Associations),
		"ErrRecordNotFound": reflect.ValueOf(&orm.ErrRecordNotFound).Elem(),
		"Observers":         reflect.ValueOf(&orm.Observers).Elem(),

		// type definitions
		"Model":       reflect.ValueOf((*orm.Model)(nil)),
		"Observer":    reflect.ValueOf((*orm.Observer)(nil)),
		"SoftDeletes": reflect.ValueOf((*orm.SoftDeletes)(nil)),
		"Timestamps":  reflect.ValueOf((*orm.Timestamps)(nil)),
	}
}
