// Code generated by 'yaegi extract github.com/hulutech-web/goravel-tinker/view/auth'. DO NOT EDIT.

package symbols

import (
	"github.com/hulutech-web/goravel-tinker/view/auth"
	"reflect"
)

func init() {
	Symbols["github.com/hulutech-web/goravel-tinker/view/auth/auth"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Get":            reflect.ValueOf(auth.Get),
		"RetString":      reflect.ValueOf(auth.RetString),
		"StartYaegiAuth": reflect.ValueOf(auth.StartYaegiAuth),
		"Store":          reflect.ValueOf(auth.Store),
	}
}
