// Code generated by 'yaegi extract github.com/hulutech-web/goravel-tinker/funcs/command'. DO NOT EDIT.

package symbols

import (
	"github.com/hulutech-web/goravel-tinker/funcs/command"
	"reflect"
)

func init() {
	Symbols["github.com/hulutech-web/goravel-tinker/funcs/command/command"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AppkeyGenerate": reflect.ValueOf(command.AppkeyGenerate),
		"Call":           reflect.ValueOf(command.Call),
		"JwtGenerate":    reflect.ValueOf(command.JwtGenerate),
	}
}
