// Code generated by 'yaegi extract github.com/hulutech-web/goravel-tinker/view/cache'. DO NOT EDIT.

package symbols

import (
	"github.com/hulutech-web/goravel-tinker/view/cache"
	"reflect"
)

func init() {
	Symbols["github.com/hulutech-web/goravel-tinker/view/cache/cache"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Get":             reflect.ValueOf(cache.Get),
		"RetString":       reflect.ValueOf(cache.RetString),
		"StartYaegiCache": reflect.ValueOf(cache.StartYaegiCache),
		"Store":           reflect.ValueOf(cache.Store),
	}
}
