// Code generated by 'yaegi extract github.com/hulutech-web/goravel-tinker/funcs/cache'. DO NOT EDIT.

package symbols

import (
	"github.com/hulutech-web/goravel-tinker/funcs/cache"
	"reflect"
)

func init() {
	Symbols["github.com/hulutech-web/goravel-tinker/funcs/cache/cache"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Get":       reflect.ValueOf(cache.Get),
		"RetString": reflect.ValueOf(cache.RetString),
		"Store":     reflect.ValueOf(cache.Store),
	}
}
