// Code generated by 'yaegi extract github.com/hulutech-web/goravel-tinker/funcs/db'. DO NOT EDIT.

package symbols

import (
	"github.com/hulutech-web/goravel-tinker/funcs/db"
	"reflect"
)

func init() {
	Symbols["github.com/hulutech-web/goravel-tinker/funcs/db/db"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BootMS": reflect.ValueOf(db.BootMS),
		"Clear":  reflect.ValueOf(db.Clear),
		"DB":     reflect.ValueOf(db.DB),

		// type definitions
		"Gorm": reflect.ValueOf((*db.Gorm)(nil)),
	}
}
