// Code generated by 'yaegi extract goravel/packages/tinker/funcs/auth'. DO NOT EDIT.

//go:build go1.23
// +build go1.23

package symbols

import (
	"goravel/packages/tinker/funcs/auth"
	"reflect"
)

func init() {
	Symbols["goravel/packages/tinker/funcs/auth/auth"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Auth":  reflect.ValueOf(auth.Auth),
		"First": reflect.ValueOf(auth.First),
	}
}
