// Code generated by 'yaegi extract goravel-tinker/funcs/cache'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package symbols

import (
	"goravel-tinker/funcs/cache"
	"reflect"
)

func init() {
	Symbols["goravel-tinker/funcs/cache/cache"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Get":       reflect.ValueOf(cache.Get),
		"RetString": reflect.ValueOf(cache.RetString),
		"Store":     reflect.ValueOf(cache.Store),
	}
}
