// Code generated by 'yaegi extract goravel/packages/tinker/funcs/command'. DO NOT EDIT.

//go:build go1.23
// +build go1.23

package symbols

import (
	"goravel/packages/tinker/funcs/command"
	"reflect"
)

func init() {
	Symbols["goravel/packages/tinker/funcs/command/command"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AppkeyGenerate": reflect.ValueOf(command.AppkeyGenerate),
		"Call":           reflect.ValueOf(command.Call),
		"JwtGenerate":    reflect.ValueOf(command.JwtGenerate),
	}
}
