// Code generated by 'yaegi extract goravel/packages/tinker/funcs/cache'. DO NOT EDIT.

//go:build go1.23
// +build go1.23

package symbols

import (
	"goravel/packages/tinker/funcs/cache"
	"reflect"
)

func init() {
	Symbols["goravel/packages/tinker/funcs/cache/cache"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Get":       reflect.ValueOf(cache.Get),
		"RetString": reflect.ValueOf(cache.RetString),
		"Store":     reflect.ValueOf(cache.Store),
	}
}
