// Code generated by 'yaegi extract goravel/app/models'. DO NOT EDIT.

//go:build go1.23
// +build go1.23

package symbols

import (
	"goravel/app/models"
	"reflect"
)

func init() {
	Symbols["goravel/app/models/models"] = map[string]reflect.Value{
		// type definitions
		"Dept": reflect.ValueOf((*models.Dept)(nil)),
		"User": reflect.ValueOf((*models.User)(nil)),
	}
}
