// Code generated by 'yaegi extract goravel/app/models'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package symbols

import (
	"goravel/app/models"
	"reflect"
)

func init() {
	Symbols["goravel/app/models/models"] = map[string]reflect.Value{
		// type definitions
		"Department": reflect.ValueOf((*models.Department)(nil)),
		"Role":       reflect.ValueOf((*models.Role)(nil)),
		"User":       reflect.ValueOf((*models.User)(nil)),
	}
}
