// Code generated by 'yaegi extract goravel/packages/tinker/funcs/query'. DO NOT EDIT.

//go:build go1.23
// +build go1.23

package symbols

import (
	"goravel/packages/tinker/funcs/query"
	"reflect"
)

func init() {
	Symbols["goravel/packages/tinker/funcs/query/query"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BootMS":      reflect.ValueOf(query.BootMS),
		"Query":       reflect.ValueOf(query.Query),
		"QueryIns":    reflect.ValueOf(&query.QueryIns).Elem(),
		"StructToMap": reflect.ValueOf(query.StructToMap),

		// type definitions
		"MyQuery": reflect.ValueOf((*query.MyQuery)(nil)),
	}
}
