// Code generated by 'yaegi extract goravel/packages/tinker/funcs/db'. DO NOT EDIT.

//go:build go1.23
// +build go1.23

package symbols

import (
	"goravel/packages/tinker/funcs/db"
	"reflect"
)

func init() {
	Symbols["goravel/packages/tinker/funcs/db/db"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BootMYSQL":     reflect.ValueOf(db.BootMYSQL),
		"Clear":         reflect.ValueOf(db.Clear),
		"DB":            reflect.ValueOf(db.DB),
		"Find":          reflect.ValueOf(db.Find),
		"Take":          reflect.ValueOf(db.Take),
		"WhereBetween":  reflect.ValueOf(db.WhereBetween),
		"WhereIn":       reflect.ValueOf(db.WhereIn),
		"WhereLike":     reflect.ValueOf(db.WhereLike),
		"WhereMap":      reflect.ValueOf(db.WhereMap),
		"WhereNot":      reflect.ValueOf(db.WhereNot),
		"WhereNotEqual": reflect.ValueOf(db.WhereNotEqual),

		// type definitions
		"Gorm": reflect.ValueOf((*db.Gorm)(nil)),
	}
}
