// Code generated by 'yaegi extract tinker/funcs/cache'. DO NOT EDIT.

//go:build go1.22
// +build go1.22

package symbols

import (
	"reflect"
	"tinker/funcs/cache"
)

func init() {
	Symbols["tinker/funcs/cache/cache"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Get":       reflect.ValueOf(cache.Get),
		"RetString": reflect.ValueOf(cache.RetString),
		"Store":     reflect.ValueOf(cache.Store),
	}
}
