// Code generated by 'yaegi extract github.com/goravel/framework/support/path'. DO NOT EDIT.

package symbol

import (
	"github.com/goravel/framework/support/path"
	"reflect"
)

func init() {
	Symbols["github.com/goravel/framework/support/path/path"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"App":        reflect.ValueOf(path.App),
		"Base":       reflect.ValueOf(path.Base),
		"Config":     reflect.ValueOf(path.Config),
		"Database":   reflect.ValueOf(path.Database),
		"Executable": reflect.ValueOf(path.Executable),
		"Public":     reflect.ValueOf(path.Public),
		"Storage":    reflect.ValueOf(path.Storage),
	}
}
