// Code generated by 'yaegi extract github.com/goravel/framework/facades'. DO NOT EDIT.

package symbol

import (
	"github.com/goravel/framework/facades"
	"reflect"
)

func init() {
	Symbols["github.com/goravel/framework/facades/facades"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"App":         reflect.ValueOf(facades.App),
		"Artisan":     reflect.ValueOf(facades.Artisan),
		"Auth":        reflect.ValueOf(facades.Auth),
		"Cache":       reflect.ValueOf(facades.Cache),
		"Config":      reflect.ValueOf(facades.Config),
		"Crypt":       reflect.ValueOf(facades.Crypt),
		"Event":       reflect.ValueOf(facades.Event),
		"Gate":        reflect.ValueOf(facades.Gate),
		"Grpc":        reflect.ValueOf(facades.Grpc),
		"Hash":        reflect.ValueOf(facades.Hash),
		"Lang":        reflect.ValueOf(facades.Lang),
		"Log":         reflect.ValueOf(facades.Log),
		"Mail":        reflect.ValueOf(facades.Mail),
		"Orm":         reflect.ValueOf(facades.Orm),
		"Queue":       reflect.ValueOf(facades.Queue),
		"RateLimiter": reflect.ValueOf(facades.RateLimiter),
		"Route":       reflect.ValueOf(facades.Route),
		"Schedule":    reflect.ValueOf(facades.Schedule),
		"Seeder":      reflect.ValueOf(facades.Seeder),
		"Session":     reflect.ValueOf(facades.Session),
		"Storage":     reflect.ValueOf(facades.Storage),
		"Testing":     reflect.ValueOf(facades.Testing),
		"Validation":  reflect.ValueOf(facades.Validation),
		"View":        reflect.ValueOf(facades.View),
	}
}
